import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;


public class LoginScreen extends CustomComponent {

    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_2;
    @AutoGenerated
    private VerticalLayout verticalLayout_1;
    @AutoGenerated
    private VerticalLayout verticalLayout_3;
    @AutoGenerated
    private Button button_4;
    @AutoGenerated
    private Button button_1;
    @AutoGenerated
    private PasswordField passwordField_1;
    @AutoGenerated
    private Label label_2;
    @AutoGenerated
    private TextField textField_1;
    @AutoGenerated
    private Label label_1;
    @AutoGenerated
    private VerticalLayout verticalLayout_2;
    @AutoGenerated
    private Button button_3;

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public LoginScreen() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("400px");
        mainLayout.setHeight("200px");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("400px");
        setHeight("200px");
        
        // horizontalLayout_2
        horizontalLayout_2 = buildHorizontalLayout_2();
        mainLayout.addComponent(horizontalLayout_2, "left:0.0px;");
        
        return mainLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_2() {
        // common part: create layout
        horizontalLayout_2 = new HorizontalLayout();
        horizontalLayout_2.setImmediate(false);
        horizontalLayout_2.setWidth("100.0%");
        horizontalLayout_2.setHeight("100.0%");
        horizontalLayout_2.setMargin(false);
        
        // verticalLayout_2
        verticalLayout_2 = buildVerticalLayout_2();
        horizontalLayout_2.addComponent(verticalLayout_2);
        horizontalLayout_2.setExpandRatio(verticalLayout_2, 1.0f);
        
        // verticalLayout_1
        verticalLayout_1 = buildVerticalLayout_1();
        horizontalLayout_2.addComponent(verticalLayout_1);
        horizontalLayout_2.setExpandRatio(verticalLayout_1, 1.0f);
        
        return horizontalLayout_2;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_2() {
        // common part: create layout
        verticalLayout_2 = new VerticalLayout();
        verticalLayout_2.setImmediate(false);
        verticalLayout_2.setWidth("100.0%");
        verticalLayout_2.setHeight("100.0%");
        verticalLayout_2.setMargin(true);
        
        // button_3
        button_3 = new Button();
        button_3.setCaption("Button");
        button_3.setImmediate(true);
        button_3.setWidth("80.0%");
        button_3.setHeight("-1px");
        verticalLayout_2.addComponent(button_3);
        verticalLayout_2.setComponentAlignment(button_3, new Alignment(33));
        
        return verticalLayout_2;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_1() {
        // common part: create layout
        verticalLayout_1 = new VerticalLayout();
        verticalLayout_1.setImmediate(false);
        verticalLayout_1.setWidth("100.0%");
        verticalLayout_1.setHeight("100.0%");
        verticalLayout_1.setMargin(true);
        
        // label_1
        label_1 = new Label();
        label_1.setImmediate(false);
        label_1.setWidth("-1px");
        label_1.setHeight("-1px");
        label_1.setValue("Label");
        verticalLayout_1.addComponent(label_1);
        
        // textField_1
        textField_1 = new TextField();
        textField_1.setImmediate(false);
        textField_1.setWidth("-1px");
        textField_1.setHeight("-1px");
        textField_1.setSecret(false);
        verticalLayout_1.addComponent(textField_1);
        
        // label_2
        label_2 = new Label();
        label_2.setImmediate(false);
        label_2.setWidth("-1px");
        label_2.setHeight("-1px");
        label_2.setValue("Label");
        verticalLayout_1.addComponent(label_2);
        
        // passwordField_1
        passwordField_1 = new PasswordField();
        passwordField_1.setImmediate(false);
        passwordField_1.setWidth("-1px");
        passwordField_1.setHeight("-1px");
        verticalLayout_1.addComponent(passwordField_1);
        
        // verticalLayout_3
        verticalLayout_3 = buildVerticalLayout_3();
        verticalLayout_1.addComponent(verticalLayout_3);
        verticalLayout_1.setExpandRatio(verticalLayout_3, 1.0f);
        
        return verticalLayout_1;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_3() {
        // common part: create layout
        verticalLayout_3 = new VerticalLayout();
        verticalLayout_3.setImmediate(false);
        verticalLayout_3.setWidth("100.0%");
        verticalLayout_3.setHeight("100.0%");
        verticalLayout_3.setMargin(false);
        
        // button_1
        button_1 = new Button();
        button_1.setCaption("Button");
        button_1.setImmediate(false);
        button_1.setWidth("100.0%");
        button_1.setHeight("-1px");
        verticalLayout_3.addComponent(button_1);
        verticalLayout_3.setComponentAlignment(button_1, new Alignment(48));
        
        // button_4
        button_4 = new Button();
        button_4.setCaption("Button");
        button_4.setImmediate(true);
        button_4.setWidth("100.0%");
        button_4.setHeight("-1px");
        verticalLayout_3.addComponent(button_4);
        verticalLayout_3.setComponentAlignment(button_4, new Alignment(20));
        
        return verticalLayout_3;
    }

}
