import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.LoginForm;
import com.vaadin.ui.VerticalLayout;


public class RegistrationWindow extends CustomComponent {

    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private VerticalLayout verticalLayout_1;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;
    @AutoGenerated
    private Button button_1;
    @AutoGenerated
    private LoginForm loginForm_1;

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public RegistrationWindow() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("400px");
        mainLayout.setHeight("500px");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("400px");
        setHeight("500px");
        
        // verticalLayout_1
        verticalLayout_1 = buildVerticalLayout_1();
        mainLayout.addComponent(verticalLayout_1, "left:0.0px;");
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_1() {
        // common part: create layout
        verticalLayout_1 = new VerticalLayout();
        verticalLayout_1.setImmediate(false);
        verticalLayout_1.setWidth("100.0%");
        verticalLayout_1.setHeight("100.0%");
        verticalLayout_1.setMargin(true);
        verticalLayout_1.setSpacing(true);
        
        // loginForm_1
        loginForm_1 = new LoginForm();
        loginForm_1.setStyleName("v-loginform");
        loginForm_1.setImmediate(false);
        loginForm_1.setWidth("-1px");
        loginForm_1.setHeight("100.0%");
        verticalLayout_1.addComponent(loginForm_1);
        verticalLayout_1.setExpandRatio(loginForm_1, 1.0f);
        verticalLayout_1.setComponentAlignment(loginForm_1, new Alignment(48));
        
        // horizontalLayout_1
        horizontalLayout_1 = buildHorizontalLayout_1();
        verticalLayout_1.addComponent(horizontalLayout_1);
        verticalLayout_1.setComponentAlignment(horizontalLayout_1,
                new Alignment(24));
        
        return verticalLayout_1;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1() {
        // common part: create layout
        horizontalLayout_1 = new HorizontalLayout();
        horizontalLayout_1.setImmediate(false);
        horizontalLayout_1.setWidth("100.0%");
        horizontalLayout_1.setHeight("-1px");
        horizontalLayout_1.setMargin(false);
        
        // button_1
        button_1 = new Button();
        button_1.setCaption("OK");
        button_1.setImmediate(false);
        button_1.setWidth("100.0%");
        button_1.setHeight("-1px");
        horizontalLayout_1.addComponent(button_1);
        horizontalLayout_1.setExpandRatio(button_1, 1.0f);
        horizontalLayout_1.setComponentAlignment(button_1, new Alignment(48));
        
        return horizontalLayout_1;
    }

}
