import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.LoginForm;
import com.vaadin.ui.VerticalLayout;


public class TicketCreator extends CustomComponent {

    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private VerticalLayout verticalLayout_1;
    @AutoGenerated
    private Button button_CalcPrice;
    @AutoGenerated
    private LoginForm loginForm_1;

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public TicketCreator() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("400px");
        mainLayout.setHeight("450px");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("400px");
        setHeight("450px");
        
        // verticalLayout_1
        verticalLayout_1 = buildVerticalLayout_1();
        mainLayout.addComponent(verticalLayout_1, "left:0.0px;");
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_1() {
        // common part: create layout
        verticalLayout_1 = new VerticalLayout();
        verticalLayout_1.setImmediate(false);
        verticalLayout_1.setWidth("100.0%");
        verticalLayout_1.setHeight("100.0%");
        verticalLayout_1.setMargin(true);
        
        // loginForm_1
        loginForm_1 = new LoginForm();
        loginForm_1.setStyleName("v-loginform");
        loginForm_1.setImmediate(false);
        loginForm_1.setWidth("100.0%");
        loginForm_1.setHeight("100.0%");
        verticalLayout_1.addComponent(loginForm_1);
        verticalLayout_1.setExpandRatio(loginForm_1, 1.0f);
        
        // button_CalcPrice
        button_CalcPrice = new Button();
        button_CalcPrice.setCaption("OK");
        button_CalcPrice.setImmediate(false);
        button_CalcPrice.setWidth("-1px");
        button_CalcPrice.setHeight("-1px");
        verticalLayout_1.addComponent(button_CalcPrice);
        verticalLayout_1.setComponentAlignment(button_CalcPrice, new Alignment(
                48));
        
        return verticalLayout_1;
    }

}
