import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.LoginForm;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;


public class UserScreen extends CustomComponent {

    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private VerticalLayout vl_main;
    @AutoGenerated
    private Accordion accordion_1;
    @AutoGenerated
    private VerticalLayout vl_ModifyUser;
    @AutoGenerated
    private HorizontalLayout hl_ModifyControls;
    @AutoGenerated
    private Button button_UserCancel;
    @AutoGenerated
    private Button button_UserSave;
    @AutoGenerated
    private LoginForm loginForm_3;
    @AutoGenerated
    private VerticalLayout vl_Reservations;
    @AutoGenerated
    private HorizontalLayout hl_myResDetails;
    @AutoGenerated
    private VerticalLayout vl_myResButtons;
    @AutoGenerated
    private Button button_ExchangeRes;
    @AutoGenerated
    private Button button_DeleteRes;
    @AutoGenerated
    private LoginForm loginForm_2;
    @AutoGenerated
    private Table table_myRes;
    @AutoGenerated
    private VerticalLayout vl_SearchAndList;
    @AutoGenerated
    private HorizontalSplitPanel hsp_Results;
    @AutoGenerated
    private VerticalLayout vl_ResultDetails;
    @AutoGenerated
    private Button button_BookFlight;
    @AutoGenerated
    private LoginForm loginForm_1;
    @AutoGenerated
    private Table table_Results;
    @AutoGenerated
    private HorizontalLayout hl_SearchControls;
    @AutoGenerated
    private Button button_SearchHotels;
    @AutoGenerated
    private Button button_SearchFlights;
    @AutoGenerated
    private TextField txtSearch;
    @AutoGenerated
    private HorizontalLayout hl_top;
    @AutoGenerated
    private Button button_logout;
    @AutoGenerated
    private Label label_currUser;

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public UserScreen() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // vl_main
        vl_main = buildVl_main();
        mainLayout.addComponent(vl_main, "top:0.0px;left:0.0px;");
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildVl_main() {
        // common part: create layout
        vl_main = new VerticalLayout();
        vl_main.setImmediate(false);
        vl_main.setWidth("100.0%");
        vl_main.setHeight("100.0%");
        vl_main.setMargin(true);
        
        // hl_top
        hl_top = buildHl_top();
        vl_main.addComponent(hl_top);
        
        // accordion_1
        accordion_1 = buildAccordion_1();
        vl_main.addComponent(accordion_1);
        vl_main.setExpandRatio(accordion_1, 1.0f);
        
        return vl_main;
    }

    @AutoGenerated
    private HorizontalLayout buildHl_top() {
        // common part: create layout
        hl_top = new HorizontalLayout();
        hl_top.setImmediate(false);
        hl_top.setWidth("100.0%");
        hl_top.setHeight("-1px");
        hl_top.setMargin(true);
        
        // label_currUser
        label_currUser = new Label();
        label_currUser.setImmediate(false);
        label_currUser.setWidth("-1px");
        label_currUser.setHeight("-1px");
        label_currUser.setValue("Label");
        hl_top.addComponent(label_currUser);
        
        // button_logout
        button_logout = new Button();
        button_logout.setCaption("Button");
        button_logout.setImmediate(true);
        button_logout.setWidth("-1px");
        button_logout.setHeight("-1px");
        hl_top.addComponent(button_logout);
        hl_top.setComponentAlignment(button_logout, new Alignment(6));
        
        return hl_top;
    }

    @AutoGenerated
    private Accordion buildAccordion_1() {
        // common part: create layout
        accordion_1 = new Accordion();
        accordion_1.setImmediate(true);
        accordion_1.setWidth("100.0%");
        accordion_1.setHeight("100.0%");
        
        // vl_SearchAndList
        vl_SearchAndList = buildVl_SearchAndList();
        accordion_1.addTab(vl_SearchAndList, "Search & List", null);
        
        // vl_Reservations
        vl_Reservations = buildVl_Reservations();
        accordion_1.addTab(vl_Reservations, "Reservations", null);
        
        // vl_ModifyUser
        vl_ModifyUser = buildVl_ModifyUser();
        accordion_1.addTab(vl_ModifyUser, "Modify User", null);
        
        return accordion_1;
    }

    @AutoGenerated
    private VerticalLayout buildVl_SearchAndList() {
        // common part: create layout
        vl_SearchAndList = new VerticalLayout();
        vl_SearchAndList.setImmediate(false);
        vl_SearchAndList.setWidth("100.0%");
        vl_SearchAndList.setHeight("100.0%");
        vl_SearchAndList.setMargin(true);
        
        // hl_SearchControls
        hl_SearchControls = buildHl_SearchControls();
        vl_SearchAndList.addComponent(hl_SearchControls);
        
        // hsp_Results
        hsp_Results = buildHsp_Results();
        vl_SearchAndList.addComponent(hsp_Results);
        vl_SearchAndList.setExpandRatio(hsp_Results, 1.0f);
        
        return vl_SearchAndList;
    }

    @AutoGenerated
    private HorizontalLayout buildHl_SearchControls() {
        // common part: create layout
        hl_SearchControls = new HorizontalLayout();
        hl_SearchControls.setImmediate(false);
        hl_SearchControls.setWidth("100.0%");
        hl_SearchControls.setHeight("-1px");
        hl_SearchControls.setMargin(false);
        hl_SearchControls.setSpacing(true);
        
        // txtSearch
        txtSearch = new TextField();
        txtSearch.setImmediate(false);
        txtSearch.setWidth("100.0%");
        txtSearch.setHeight("-1px");
        txtSearch.setSecret(false);
        hl_SearchControls.addComponent(txtSearch);
        hl_SearchControls.setExpandRatio(txtSearch, 1.0f);
        
        // button_SearchFlights
        button_SearchFlights = new Button();
        button_SearchFlights.setCaption("Search");
        button_SearchFlights.setImmediate(true);
        button_SearchFlights.setWidth("-1px");
        button_SearchFlights.setHeight("-1px");
        hl_SearchControls.addComponent(button_SearchFlights);
        
        // button_SearchHotels
        button_SearchHotels = new Button();
        button_SearchHotels.setCaption("Button");
        button_SearchHotels.setImmediate(true);
        button_SearchHotels.setWidth("-1px");
        button_SearchHotels.setHeight("-1px");
        hl_SearchControls.addComponent(button_SearchHotels);
        
        return hl_SearchControls;
    }

    @AutoGenerated
    private HorizontalSplitPanel buildHsp_Results() {
        // common part: create layout
        hsp_Results = new HorizontalSplitPanel();
        hsp_Results.setImmediate(false);
        hsp_Results.setWidth("100.0%");
        hsp_Results.setHeight("100.0%");
        hsp_Results.setMargin(false);
        
        // table_Results
        table_Results = new Table();
        table_Results.setImmediate(false);
        table_Results.setWidth("100.0%");
        table_Results.setHeight("100.0%");
        hsp_Results.addComponent(table_Results);
        
        // vl_ResultDetails
        vl_ResultDetails = buildVl_ResultDetails();
        hsp_Results.addComponent(vl_ResultDetails);
        
        return hsp_Results;
    }

    @AutoGenerated
    private VerticalLayout buildVl_ResultDetails() {
        // common part: create layout
        vl_ResultDetails = new VerticalLayout();
        vl_ResultDetails.setImmediate(false);
        vl_ResultDetails.setWidth("100.0%");
        vl_ResultDetails.setHeight("100.0%");
        vl_ResultDetails.setMargin(true);
        
        // loginForm_1
        loginForm_1 = new LoginForm();
        loginForm_1.setStyleName("v-loginform");
        loginForm_1.setImmediate(false);
        loginForm_1.setWidth("-1px");
        loginForm_1.setHeight("100.0%");
        vl_ResultDetails.addComponent(loginForm_1);
        vl_ResultDetails.setExpandRatio(loginForm_1, 1.0f);
        vl_ResultDetails.setComponentAlignment(loginForm_1, new Alignment(48));
        
        // button_BookFlight
        button_BookFlight = new Button();
        button_BookFlight.setCaption("Book Flight");
        button_BookFlight.setImmediate(true);
        button_BookFlight.setWidth("-1px");
        button_BookFlight.setHeight("-1px");
        vl_ResultDetails.addComponent(button_BookFlight);
        vl_ResultDetails.setComponentAlignment(button_BookFlight,
                new Alignment(48));
        
        return vl_ResultDetails;
    }

    @AutoGenerated
    private VerticalLayout buildVl_Reservations() {
        // common part: create layout
        vl_Reservations = new VerticalLayout();
        vl_Reservations.setImmediate(false);
        vl_Reservations.setWidth("100.0%");
        vl_Reservations.setHeight("100.0%");
        vl_Reservations.setMargin(true);
        
        // table_myRes
        table_myRes = new Table();
        table_myRes.setImmediate(false);
        table_myRes.setWidth("100.0%");
        table_myRes.setHeight("100.0%");
        vl_Reservations.addComponent(table_myRes);
        vl_Reservations.setExpandRatio(table_myRes, 1.0f);
        
        // hl_myResDetails
        hl_myResDetails = buildHl_myResDetails();
        vl_Reservations.addComponent(hl_myResDetails);
        vl_Reservations.setExpandRatio(hl_myResDetails, 1.0f);
        
        return vl_Reservations;
    }

    @AutoGenerated
    private HorizontalLayout buildHl_myResDetails() {
        // common part: create layout
        hl_myResDetails = new HorizontalLayout();
        hl_myResDetails.setImmediate(false);
        hl_myResDetails.setWidth("100.0%");
        hl_myResDetails.setHeight("100.0%");
        hl_myResDetails.setMargin(true);
        
        // loginForm_2
        loginForm_2 = new LoginForm();
        loginForm_2.setStyleName("v-loginform");
        loginForm_2.setImmediate(false);
        loginForm_2.setWidth("100.0%");
        loginForm_2.setHeight("100.0%");
        hl_myResDetails.addComponent(loginForm_2);
        hl_myResDetails.setExpandRatio(loginForm_2, 1.0f);
        
        // vl_myResButtons
        vl_myResButtons = buildVl_myResButtons();
        hl_myResDetails.addComponent(vl_myResButtons);
        
        return hl_myResDetails;
    }

    @AutoGenerated
    private VerticalLayout buildVl_myResButtons() {
        // common part: create layout
        vl_myResButtons = new VerticalLayout();
        vl_myResButtons.setImmediate(false);
        vl_myResButtons.setWidth("-1px");
        vl_myResButtons.setHeight("100.0%");
        vl_myResButtons.setMargin(true);
        vl_myResButtons.setSpacing(true);
        
        // button_DeleteRes
        button_DeleteRes = new Button();
        button_DeleteRes.setCaption("Delete");
        button_DeleteRes.setImmediate(true);
        button_DeleteRes.setWidth("-1px");
        button_DeleteRes.setHeight("-1px");
        vl_myResButtons.addComponent(button_DeleteRes);
        vl_myResButtons.setComponentAlignment(button_DeleteRes, new Alignment(
                24));
        
        // button_ExchangeRes
        button_ExchangeRes = new Button();
        button_ExchangeRes.setCaption("Change");
        button_ExchangeRes.setImmediate(true);
        button_ExchangeRes.setWidth("-1px");
        button_ExchangeRes.setHeight("-1px");
        vl_myResButtons.addComponent(button_ExchangeRes);
        vl_myResButtons.setComponentAlignment(button_ExchangeRes,
                new Alignment(20));
        
        return vl_myResButtons;
    }

    @AutoGenerated
    private VerticalLayout buildVl_ModifyUser() {
        // common part: create layout
        vl_ModifyUser = new VerticalLayout();
        vl_ModifyUser.setImmediate(false);
        vl_ModifyUser.setWidth("100.0%");
        vl_ModifyUser.setHeight("100.0%");
        vl_ModifyUser.setMargin(true);
        
        // loginForm_3
        loginForm_3 = new LoginForm();
        loginForm_3.setStyleName("v-loginform");
        loginForm_3.setImmediate(false);
        loginForm_3.setWidth("100.0%");
        loginForm_3.setHeight("100.0%");
        vl_ModifyUser.addComponent(loginForm_3);
        vl_ModifyUser.setExpandRatio(loginForm_3, 1.0f);
        
        // hl_ModifyControls
        hl_ModifyControls = buildHl_ModifyControls();
        vl_ModifyUser.addComponent(hl_ModifyControls);
        
        return vl_ModifyUser;
    }

    @AutoGenerated
    private HorizontalLayout buildHl_ModifyControls() {
        // common part: create layout
        hl_ModifyControls = new HorizontalLayout();
        hl_ModifyControls.setImmediate(false);
        hl_ModifyControls.setWidth("-1px");
        hl_ModifyControls.setHeight("-1px");
        hl_ModifyControls.setMargin(false);
        
        // button_UserSave
        button_UserSave = new Button();
        button_UserSave.setCaption("Save");
        button_UserSave.setImmediate(true);
        button_UserSave.setWidth("-1px");
        button_UserSave.setHeight("-1px");
        hl_ModifyControls.addComponent(button_UserSave);
        
        // button_UserCancel
        button_UserCancel = new Button();
        button_UserCancel.setCaption("Cancel");
        button_UserCancel.setImmediate(true);
        button_UserCancel.setWidth("-1px");
        button_UserCancel.setHeight("-1px");
        hl_ModifyControls.addComponent(button_UserCancel);
        
        return hl_ModifyControls;
    }

}
